swagger: "2.0"
basePath: "/v1"
info:
  description: ""
  version: "1.0.0"
  title: "Query geography"
schemes:
- "http"
paths:
  /area-types:
    get:
      summary: "Get list of area types for given dataset "
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: dataset
          type: string
          in: query
          required: false
      responses:
        200:
          description: "area types returned successfully"
          schema:
            $ref: '#/definitions/GetAreaTypesResponse'
        401:
          $ref: '#/responses/Unauthorised'
        404:
          description: "Dataset not found"
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          $ref: '#/responses/InternalServerError'
        502:
          $ref: '#/responses/BadGateway'
  /area-types/{area-type}:
    get:
      parameters:
      - name: area-type
        type: string
        in: path
        required: true
      - name: q
        type: string
        in: query
        required: false
      summary: "Get categories/values for given area type"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Categories for area type returned"
          schema:
            $ref: '#/definitions/GetAreaTypeResponse'
  /areas:
    get:
      parameters:
      - name: area-type
        type: string
        in: query
        required: true
      summary: "Get categories/values for given area type"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "Categories for area type returned"
          schema:
            $ref: '#/definitions/GetAreasResponse'
  /area-types/{area-type}/parents:
    get:
      summary: "Get list of parents for given area type"
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: area-type
          type: string
          in: path
          required: true
      responses:
        200:
          description: "parent area types returned successfully"
          schema:
            $ref: '#/definitions/GetAreaTypeParentsResponse'
  /dimensions:
    get:
      summary: "Get list of geography dimensions for given Dataset "
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: dataset
          type: string
          in: query
          required: true
      responses:
        200:
          description: "dimensions returned successfully"
          schema:
            $ref: '#/definitions/GetDimensionsResponse'
  /dimension/{dimension}/options:
    get:
      summary: "Get list of options for given dimension "
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: dimension
          type: string
          in: path
          required: true
      responses:
        200:
          description: "area types returned successfully"
          schema:
            $ref: '#/definitions/GetDimensionOptionsResponse'
responses:
  Unauthorised:
    description: "The token provided is unauthorised to carry out this operation"
  InternalServerError:
    description: "Failed to process the request due to an internal error"
  BadGateway:
    description: "Failed to process the request due to an error in a downstream server"
definitions:
  GetAreaTypesResponse:
    description: "The response body containing all available area-types for a given dataset"
    properties:
      area-types:
        type: array
        items:
          $ref: '#/definitions/AreaType'
        example: 
        - id: "electoral_wards"
          label: "Electoral Wards or Divisions"
        - id: "region"
          label: "Region"
        - id: "city"
          label: "City"
  GetAreaTypeResponse:
    description: "The response body containing all available area-types for a given dataset"
    properties:
      area-type:
        allOf:
          - $ref: '#/definitions/AreaType'
          - example:
              id: "electoral_wards"
              label: "Electoral Wards or Divisions"
  GetAreasResponse:
    description: "The response body containing areas for a given area type"
    properties:
      areas:
        type: array
        items:
          $ref: '#/definitions/Area'
        example: 
        - id: "STJGGC1"
          label: "St John's"
          parent: "Bromsgrove"
        - id: "STJAB34"
          label: "St John's"
          parent: "Fyide"
        - id: "SB498GFF4"
          label: "Southborough North"
          parent: "Tunbridge Wells"
  GetAreaTypeParentsResponse:
    description: "The response body containing parents of area-type"
    properties:
      area-types:
        type: array
        items:
          $ref: '#/definitions/AreaType'
        example: 
        - id: "country"
          label: "Country"
        - id: "region"
          label: "Region"
        - id: "city"
          label: "City"
  AreaType:
    properties:
      id:
        type: string
      label:
        type: string
  Area:
    properties:
      id:
        type: string
      label:
        type: string
      parent:
        type: string
  GetDimensionsResponse:
    description: "The response body containing dimensions for a given dataset"
    properties:
      dimensions:
        type: array
        items:
          $ref: '#/definitions/Dimension'
        example: 
        - name: "city"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          options:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1/dimensions/city/options"
            id: "city"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
        - name: "region"
          code_list:
            href: "http://localhost:22400/code-lists/region"
            id: "region"
          options:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1/dimensions/region/options"
            id: "city"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
  GetDimensionOptionsResponse:
    description: "The response body containing options for a given Dimension"
    properties:
      options:
        type: array
        items:
          $ref: '#/definitions/DimensionOption'
        example: 
        - label: "Liverpool"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          code:
            href: "http://localhost:22400/code-lists/city/codes/1"
            id: "1"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"            
        - name: "Belfast"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          code:
            href: "http://localhost:22400/code-lists/city/codes/2"
            id: "2"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
  ErrorResponse:
    description: "The response body containing an error message"
    properties:
      errors:
        type: array
        items:
          type: string
  Dimension:
    properties:
      name:
        type: string
      links:
        type: object
        properties:
          code_list:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          options:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          version:
            type: object
            properties:
              href:
                type: string
  DimensionOption:
    properties:
      name:
        type: string
      links:
        type: object
        properties:
          code_list:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          code:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          version:
            type: object
            properties:
              href:
                type: string
